sudo: required
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain 1.37.0 -y
  - source $HOME/.cargo/env
  - rustup target add wasm32-unknown-unknown
  - cargo install wasm-bindgen-cli wasm-pack
  - npm run build-prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
notifications:
  email:
    recipients:
      - $my_email
    on_success: always
    on_failure: always
