[package]
name = "react_rust_wasm"
version = "1.0.0"

[lib]
crate-type = ["cdylib"]
path = "./src/tile_solver_rust/lib.rs"

[dependencies]
wasm-bindgen = "0.2"
rand = "0.7.0"
lazy_static = "1.3.0"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]
